name: aklima-foundation
metadata:
  template: azd-init@1.18.2
workflows:
  up:
    - azd: provision
    - azd: deploy
services:
  web:
    project: ./
    dist: out
    host: staticwebapp
    language: ts
    hooks:
      prebuild:
        shell: sh
        run: npm install
      build:
        shell: sh
        run: npm run build
